### ISSUE TITLE
Would you mind adding a license?

### ISSUE THREAD

**Issue by eqyiel** [snosrap/xpc_set_event_stream_handler#1]
This is useful for people who want to remap keys using `hidutil`.

I want to package this and add it to https://github.com/NixOS/nixpkgs, but according to the source file, [this is not permitted](https://choosealicense.com/no-permission/).

https://github.com/snosrap/xpc_set_event_stream_handler/blob/5382ab705365e460a920d65a2e06015e471c13bf/xpc_set_event_stream_handler/main.m#L6

Would you consider licensing this under MIT or similar?

**Comment by snosrap** [comment]
Thanks for the suggestion. Added MIT license.
