### ISSUE TITLE
Using it with BLUETOOTH audio device?

### ISSUE THREAD

**Issue by vlad-cotfas** [snosrap/xpc_set_event_stream_handler#3]
How I can detect the BLE connect/disconnect?

Says in your doc:
`IOProviderClass` should be either `IOPCIDevice` (Thunderbolt) or `IOUSBDevice` (USB).

**Comment by vlad-cotfas** [comment]
Found it myself

				<key>IOProviderClass</key>
				<string>IOBluetoothDevice</string>

And you can monitor the BLE device via Additional_Tools_for_Xcode_12.5.dmg (Catalina XCODE 12.4) > Hardware > IORegistryExplorer

**Comment by snosrap** [comment]
Nice find, thanks @cotfas!
